FROM node:22-alpine AS builder

WORKDIR /app

# Copy root manifests and lockfiles
COPY package*.json tsconfig.json ./
COPY packages ./packages
COPY apps ./apps
COPY scripts ./scripts

# Install dependencies and build
RUN npm install
RUN npm run build:packages

EXPOSE 4000 4001 4002 4003 4004 4005 4006 4007 4008 4009

CMD ["npm", "run", "start"]
